### ISSUE TITLE
downsample step 

### ISSUE THREAD

**Issue by jonathan-chan-etrovub** [bkong999/COVNet#13]
![image_2020_05_01T11_56_02_129Z](https://user-images.githubusercontent.com/64106300/80809464-0874a580-8bc2-11ea-9f9e-18d53997a81b.png)
We are checking with our data the preprocessing step. Pls refer to attached image. The output of the downsample step show an augmented image, can you help? Thanks.

**Comment by bkong999** [comment]
> ![image_2020_05_01T11_56_02_129Z](https://user-images.githubusercontent.com/64106300/80809464-0874a580-8bc2-11ea-9f9e-18d53997a81b.png)
> We are checking with our data the preprocessing step. Pls refer to attached image. The output of the downsample step show an augmented image, can you help? Thanks.

Hello jonathan-chan-etrovub,

For your reference, my preprocessing steps are as follows: First, I generate the mask image. Then I augment the lesions with MIP and resample both the MIPed image and the binary mask. The final preprocessed image is generated by masking the augmented image with the mask.

**Comment by Tianyangg** [comment]
> ![image_2020_05_01T11_56_02_129Z](https://user-images.githubusercontent.com/64106300/80809464-0874a580-8bc2-11ea-9f9e-18d53997a81b.png)
> We are checking with our data the preprocessing step. Pls refer to attached image. The output of the downsample step show an augmented image, can you help? Thanks.

Hello jonathan-chan-etrovub,
Which dataset are you using at the moment? 
THX :))

**Comment by jonathan-chan-etrovub** [comment]
> > ![image_2020_05_01T11_56_02_129Z](https://user-images.githubusercontent.com/64106300/80809464-0874a580-8bc2-11ea-9f9e-18d53997a81b.png)
> > We are checking with our data the preprocessing step. Pls refer to attached image. The output of the downsample step show an augmented image, can you help? Thanks.
> 
> Hello jonathan-chan-etrovub,
> Which dataset are you using at the moment?
> THX :))

This is a European dataset, unfortunately not public.

**Comment by jonathan-chan-etrovub** [comment]
> > ![image_2020_05_01T11_56_02_129Z](https://user-images.githubusercontent.com/64106300/80809464-0874a580-8bc2-11ea-9f9e-18d53997a81b.png)
> > We are checking with our data the preprocessing step. Pls refer to attached image. The output of the downsample step show an augmented image, can you help? Thanks.
> 
> Hello jonathan-chan-etrovub,
> 
> For your reference, my preprocessing steps are as follows: First, I generate the mask image. Then I augment the lesions with MIP and resample both the MIPed image and the binary mask. The final preprocessed image is generated by masking the augmented image with the mask.

Thanks. We have used a different resample function in house, its our problem. I will follow similar discussion on preprocessing in other link/issue
