### ISSUE TITLE
Input data shapes (dataset.py)

### ISSUE THREAD

**Issue by ndahiya3** [bkong999/COVNet#14]
If I understand correctly, the input to the model is 3D CT image. What does line 59 of dataset.py (full_channel = np.stack([array, array, array])) do ?
It converts data to 4D? [3 slices W H] ? Its not clear why? With further addition of batch dimension and permutation (line 71 dataset.py full_channel = torch.FloatTensor(full_channel).permute((1, 0, 2, 3)) ) the output becomes: [batch_size slices 3 W H].

This throws error further down the line when passing 5D data to pretrained model which expects 4D data?

Could anyone clarify this issue and shed some light on it?

**Comment by bkong999** [comment]
> If I understand correctly, the input to the model is 3D CT image. What does line 59 of dataset.py (full_channel = np.stack([array, array, array])) do ?
> It converts data to 4D? [3 slices W H] ? Its not clear why? With further addition of batch dimension and permutation (line 71 dataset.py full_channel = torch.FloatTensor(full_channel).permute((1, 0, 2, 3)) ) the output becomes: [batch_size slices 3 W H].
> 
> This throws error further down the line when passing 5D data to pretrained model which expects 4D data?
> 
> Could anyone clarify this issue and shed some light on it?

Hello ndahiya3,

We replicate the image 3 times (full_channel = np.stack([array, array, array])) because Resnet requires an image of 3 channels. Line 75 (full_channel = torch.FloatTensor(full_channel).permute((1, 0, 2, 3))) does not introduce an additional dimension. It just transposes the first and second dimensions.

**Comment by ndahiya3** [comment]
Hi bkong999,

Thanks for the quick reply. I appreciate it.
From my understanding from reading the associated paper, the input to resnet50 is a 3D CT image, right? That would mean the number of slices should be the channels? Or am I understanding it incorrectly?

I am trying to load 3D images, which when replicated 3 times, makes 4D and after addition of batch dimension makes 5D. And that obviously doesn't work during convolution operations.

Kindly let me know what you think. I appreciate your response.
Thanks!

**Comment by ndahiya3** [comment]
Accidentally closed the issue. Sorry.

**Comment by bkong999** [comment]
> Hi bkong999,
> 
> Thanks for the quick reply. I appreciate it.
> From my understanding from reading the associated paper, the input to resnet50 is a 3D CT image, right? That would mean the number of slices should be the channels? Or am I understanding it incorrectly?
> 
> I am trying to load 3D images, which when replicated 3 times, makes 4D and after addition of batch dimension makes 5D. And that obviously doesn't work during convolution operations.
> 
> Kindly let me know what you think. I appreciate your response.
> Thanks!

 The number of slices is the batch dimension for resnet50. The number of channels is 3 as we replicated 3 times. Actually, all you have to do is to follow the preprocessing steps and then resize the image to 224x224xZ. Our code will do the rest for you.
