### ISSUE TITLE
How to train model with multiple GPU

### ISSUE THREAD

**Issue by kexianer** [bkong999/COVNet#16]
hi, 
One CT contains hundreds of slices, and one GPU's memory is insufficient for the training model。How How to solve this problem？
Thanks!

**Comment by bkong999** [comment]
> hi,
> One CT contains hundreds of slices, and one GPU's memory is insufficient for the training model。How How to solve this problem？
> Thanks!

Hello kexianer,

Please follow the Appendix E1 section of our paper for the implementation details. You can downsample your data in the z-dimension in order to fit it in the GPU. Currently, this code doesn't support multi-GPU training as the CT data has variable number of slices. In order to support multi-GPU training, you can pad the CT data to the same shape and use nn.DataParallel class in Pytorch to wrap your model. However, this will take some effort.

**Comment by kexianer** [comment]
> > hi,
> > One CT contains hundreds of slices, and one GPU's memory is insufficient for the training model。How How to solve this problem？
> > Thanks!
> 
> Hello kexianer,
> 
> Please follow the Appendix E1 section of our paper for the implementation details. You can downsample your data in the z-dimension in order to fit it in the GPU. Currently, this code doesn't support multi-GPU training as the CT data has variable number of slices. In order to support multi-GPU training, you can pad the CT data to the same shape and use nn.DataParallel class in Pytorch to wrap your model. However, this will take some effort.

**Comment by kexianer** [comment]
Thanks.
I have tried to downsample data in the z-dimension to in the z-dimension and train my model, and get a workable result. 
I would like to know, since I have done the down sampling for training, do I also need to do the down sampling for testing? Or can I use the original data to test?

**Comment by bkong999** [comment]
> Thanks.
> I have tried to downsample data in the z-dimension to in the z-dimension and train my model, and get a workable result.
> I would like to know, since I have done the down sampling for training, do I also need to do the down sampling for testing? Or can I use the original data to test?

You can use the original data. However, since the model is trained on a down-sampled dataset, I guess the results will be inferior if you test it on the original data. I think it's better to use the same preprocessing pipeline on both the training and testing data.
