### ISSUE TITLE
Is it possible to share training data to reproduce the results?

### ISSUE THREAD

**Issue by roywei** [bkong999/COVNet#2]
I would like to try this model, could you share some data if possible?
Thanks and great work!

**Comment by fengwang** [comment]
I think you need to contact the author directly at  xiajun@email.szu.edu.cn

**Comment by bkong999** [comment]
Thanks for the interest in our work.  Unfortunately, we do not own the data, and we have to get permission from our collaborators before we share the data and model.  We will update later.
