### ISSUE TITLE
All slices were considered for a volume or selected ones ?

### ISSUE THREAD

**Issue by jaskirat111** [bkong999/COVNet#20]
Each volume contains different variations of slices . All slices were considered or middle ones?

**Comment by bkong999** [comment]
> Each volume contains different variations of slices . All slices were considered or middle ones?

Hello jaskirat111,

All slices are considered in our work. To reduce the impact of the variations of non-lung regions, we only used the lung region for classification. For more details, please refer to the [Appendix E1 section](https://rsna-prod-cdn.literatumonline.com/journals/content/radiology/0/radiology.ahead-of-print/radiol.2020200905/20200319/suppl/ry_200905_supp_in%20press.pdf?b92b4ad1b4f274c70877518511abb28bed2c6f7421a565d9f7a5b3e3f5a40bc644191f5cacfb3cc9bc55304dc1db665382416f3d99ae215c8c2c697819a2d31ca928bf2079f96cd98d505bc03114c4c540dd31718f1d5225627d6304cff5910aeef4c219a8947a0212834d08ab9257ded18af9dc01b627ff30306760fd9284a3eddfb35eaaa11fc7f2a171a429faa678a82de3d50c63ff72833fbc88e36deb4f7046f64638) of our work.
