### ISSUE TITLE
Voxel Intensity Clipping 

### ISSUE THREAD

**Issue by hikmet-demir** [bkong999/COVNet#22]
Hi,

In the dataset.py, code is clipping hu values to -1250 to 250 but in the appendix E, you mentioned 

"Then, the voxel intensity values were first clipped using a window/level of 1500HU/-500HU and were then normalized to the range of [0, 1]. "

Could you explain which one did you choose (-1250,250) or (-500,1500) or something else? Also can you explain the motivation behind clipping

Thank you! Great work!

**Comment by bkong999** [comment]
> Hi,
> 
> In the dataset.py, code is clipping hu values to -1250 to 250 but in the appendix E, you mentioned
> 
> "Then, the voxel intensity values were first clipped using a window/level of 1500HU/-500HU and were then normalized to the range of [0, 1]. "
> 
> Could you explain which one did you choose (-1250,250) or (-500,1500) or something else? Also can you explain the motivation behind clipping
> 
> Thank you! Great work!

Hello hikmet-demir,

Thanks for your interest in our work. The intensity in the nifty files and the hu are two different concepts and a certain equation can be used to transform one into the other. For our dataset, intensity values -1250 and 250 are exactly the same as 1500HU/-500HU.

I am not an expert for CT imaging and I am not sure whether these values also suit your data. I guess you need to consult the people to give you the data regarding this issue.
