### ISSUE TITLE
MIP as pre-processing step

### ISSUE THREAD

**Issue by bartmch** [bkong999/COVNet#23]
Hi, I couldn't find back the MIP usage to boost lesion signals as mentioned in the appendix of your article: "To reduce the influence of vascular structure and boost the signals of
the lesions, a maximum intensity projection (MIP) algorithm was also applied to each of the slices".

Could you tell me whether I missed the implementation of this step in your code? If I didn't, why wasn't it implemented and would it be possible to explain in detail what you mean with "a MIP algorithm was applied to each of the slices"? Taking a MIP reduces your amount of slices, it's even often applied in such a way that you only have a single MIP slice.
Thank you.

**Comment by bkong999** [comment]
> Hi, I couldn't find back the MIP usage to boost lesion signals as mentioned in the appendix of your article: "To reduce the influence of vascular structure and boost the signals of
> the lesions, a maximum intensity projection (MIP) algorithm was also applied to each of the slices".
> 
> Could you tell me whether I missed the implementation of this step in your code? If I didn't, why wasn't it implemented and would it be possible to explain in detail what you mean with "a MIP algorithm was applied to each of the slices"? Taking a MIP reduces your amount of slices, it's even often applied in such a way that you only have a single MIP slice.
> Thank you.

Hello bartmch,

In this repository, only the core training and testing pipeline code are uploaded. You can refer to [this repository](https://github.com/ljpadam/maximum_intensity_projection/blob/master/maximum_intensity_projection.py) for the MIP implementation. Our MIP implementation is quite similar.

Thanks for your attention!

**Comment by joaco18** [comment]
Hi! Do you use the same 15 slices window for the MIP as the default value in [the repository](https://github.com/ljpadam/maximum_intensity_projection/blob/master/maximum_intensity_projection.py) code?

**Comment by joaco18** [comment]
Also, following the appendix E1, there you say that the MIP projections are done after the downsampling in z direction. Is that right? Wouldn't it be better to do it before the downsamping, so there you loose less information?
