### ISSUE TITLE
Resolved typo with utils.py 

### ISSUE THREAD

**Issue by mickalus1** [bkong999/COVNet#24]
Great code training fine on my data. I changed the output classes to 2 and get an error in the utils.py file.

Changing the "2" to "(n_classes-1)" on lines 96 & 98 lets it run fine so I presume it is a typo.

Cheers.

**Comment by bkong999** [comment]
> Great code training fine on my data. I changed the output classes to 2 and get an error in the utils.py file.
> 
> Changing the "2" to "(n_classes-1)" on lines 96 & 98 lets it run fine so I presume it is a typo.
> 
> Cheers.

Thanks a lot for reporting this issue. nguyenhoa93 had sent a [pull request](https://github.com/bkong999/COVNet/pull/21#issue-432121182) for this issue. Obviously, it is still not completely resolved. I will fix this problem right now.
