### ISSUE TITLE
MIP projections

### ISSUE THREAD

**Issue by joaco18** [bkong999/COVNet#25]
Hi! 
I've already made a comment in an another issue, but I think it's probably better to open a new one.
How many slices did you consider in the MIP projection? In the example code you shared, they used a sliding window of 15 slices, you did it in the same way?
Also, the MIP projections were done after or before downsampling in the z axis of the volume?
Thank you!!

**Comment by bkong999** [comment]
Hello joaco,

Thanks for your interests. The MIP projection is conducted before downsampling to avoid losing more information. A sliding window of 5 is used in our experiments.

**Comment by joaco18** [comment]
Thank you for your answer. In addition to that, I guess you do the MIP projection after de resizing to 1mm in z direction, so there the sliding window always contains 5mm of volume and the MIPs are independent of the original slice thickness of the volume. Am I right? 
If not you could be doing a mip projection of 15mm -in z axis- in a volume with 3mm of slice thickness and 5mm in one with 1mm slice thickness.

**Comment by bkong999** [comment]
> Thank you for your answer. In addition to that, I guess you do the MIP projection after de resizing to 1mm in z direction, so there the sliding window always contains 5mm of volume and the MIPs are independent of the original slice thickness of the volume. Am I right?
> If not you could be doing a mip projection of 15mm -in z axis- in a volume with 3mm of slice thickness and 5mm in one with 1mm slice thickness.



> Thank you for your answer. In addition to that, I guess you do the MIP projection after de resizing to 1mm in z direction, so there the sliding window always contains 5mm of volume and the MIPs are independent of the original slice thickness of the volume. Am I right?
> If not you could be doing a mip projection of 15mm -in z axis- in a volume with 3mm of slice thickness and 5mm in one with 1mm slice thickness.

Yes, exactly. The resampling procedure is before the MIP projection.
