### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by husam1986** [bkong999/COVNet#3]
thank you a lot . form where can i get the dataset

**Comment by banderlog** [comment]
I believe that they will never share it

**Comment by nazib** [comment]
is there any CT dataset available for covid-19. Without dataset it is difficult to varify this model.

**Comment by bkong999** [comment]
Thanks for the interest in our work. Unfortunately, we do not own the data, and we have to get permission from our collaborators before we share the data and model. We will update later.
