### ISSUE TITLE
Weights checkpoint

### ISSUE THREAD

**Issue by joaco18** [bkong999/COVNet#4]
Hi! Thanks for your work. I order to use and fine-tune your model with local data from different parts of the world, it would be nice if you could share the weights of the model you chose for predictions, and the model (and weights) of the pre-processing Unet.
I know it's very difficult to share the entire Covid-19 patients dataset, but those weights can make a great step in order to fight this disease and also validate your results.
Thanks!

**Comment by liubaoryol** [comment]
Indeed, I am asking the same. I am a student from Mexico and do not have this type of data, however me and another group of students, wwe would like to implement this model, do transfer learning on a Mexican, possibly smaller dataset, and provide it to medical institutions and hospitals to help classify COVID-19! It would be of huge help if the weights of the model are shared. We will make an ethical use of it and make the proper citation to the work and the huge help provided by Lin Li and the team!

**Comment by banderlog** [comment]
I believe that they will never share it, it look like another non-replicative NN from chinese authors.

**Comment by JoHof** [comment]
Sad, I can not really comprehend why they refuse to share the weights. However, I think I can help you with the segmentation [https://github.com/JoHof/lungmask](https://github.com/JoHof/lungmask). Works quite well for COVID-19 cases.

**Comment by banderlog** [comment]
I have certain doubts about their dataset, because they used like 1/3 COVID, 1/3 non-pneumonia and 1/3 of CAP.

CAP is community acquired pneumonia, and they are bacterial in general.  Among those CAP patients, only 210 "received laboratory confirmation of the etiology" with 28 viral pneumonias among them.

Thus their network could just learn how to differentiate viral pneumonia from any other (it is not hard task, usually).

**Comment by JoHof** [comment]
@banderlog thanks for that information! I assumed that CAP vs COVID was a bit more challenging. There might also be some bias induced by different scanner parameters in the cohorts.

**Comment by bkong999** [comment]
Thanks for the interest in our work. Unfortunately, we do not own the data, and we have to get permission from our collaborators before we share the data and model. We will update later.
