### ISSUE TITLE
Best model checkpoint

### ISSUE THREAD

**Issue by liubaoryol** [bkong999/COVNet#5]
It would be very useful if you could share the weights of your best model, to apply transfer learning and replicate it on the dataset of CT scans I acquired (which is much smaller than the one used for this repository). It would be of huge help now, during coronavirus season.

Proper reference to the original work will be made!

Thank you in advance

**Comment by emanuele** [comment]
Same for me. I have the opportunity to access the equivalent data in our local hospital in Italy and to deploy this network to support early diagnosis, but the number of images is way smaller than the one described in the publication (Zhang et al. 2020). Could you please share the pre-trained network? Either publicly or individually via agreement. Some days ago I tried to contact the corresponding author, Jun Xia, but no answer so far...

**Comment by hnguyentt** [comment]
Can't agree more. Hope they will share the pre-trained models. We don't have enough data to replicate the training.

**Comment by bkong999** [comment]
Thanks for the interest in our work. Unfortunately, we do not own the data, and we have to get permission from our collaborators before we share the data and model. We will update later.
